version: '3.8'

services:
  youtube-shorts-automation:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./output:/app/output
    environment:
      - TZ=Asia/Seoul
      - REDIRECT_URI=https://youtube-shorts-automation-381688299677.asia-northeast3.run.app/auth/callback
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    restart: unless-stopped 